version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-jessie
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    steps:
      - checkout
      - run:
          name: Update ruby
          command: 'bundle install'
      - run:
          name: update git config
          command: git config --global user.email "rockerhieu+circleci@gmail.com" && git config --global user.name "Circle CI"
      - run:
          name: generate HTML
          command: bundle exec jekyll build
  test:
    docker:
      - image: circleci/ruby:2.5-node-jessie
    steps:
      - checkout
      - run: /bin/true
  deploy:
    docker:
      - image: circleci/ruby:2.5-node-jessie
    steps:
      - checkout
      - run: ./deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master